editable/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('parrafos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parrafos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mostrar_texto, name='mostrar_texto'),
    path('anadir/', views.anadir_parrafo, name='anadir_parrafo'),
]

parrafos/models.py
from django.db import models

class Parrafo(models.Model):
    titulo = models.CharField(max_length=200)
    texto = models.TextField()  # Quill content will be stored as HTML
    autor = models.CharField(max_length=100, blank=True, null=True)  # Añadir campo autor
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

    def get_anchor(self):
        return f"parrafo-{self.pk}"

parrafos/forms.py
from django import forms
from .models import Parrafo
from bs4 import BeautifulSoup
import base64
from io import BytesIO
from PIL import Image

class ParrafoForm(forms.ModelForm):
    class Meta:
        model = Parrafo
        fields = ['titulo', 'texto', 'autor']
        widgets = {
            'titulo': forms.TextInput(attrs={'placeholder': 'Título'}),
            'texto': forms.Textarea(attrs={'placeholder': 'Escribe tu párrafo aquí...'}),
            'autor': forms.TextInput(attrs={'placeholder': 'Escrito por'})
        }

    def clean_texto(self):
        texto = self.cleaned_data.get('texto')
        soup = BeautifulSoup(texto, 'html.parser')
        for img in soup.find_all('img'):
            if 'data:image' in img['src']:  # Check if image is base64 encoded
                base64_str = img['src'].split(',')[1]
                decoded_img = base64.b64decode(base64_str)
                img_io = BytesIO(decoded_img)
                if img_io.getbuffer().nbytes > 2 * 1024 * 1024:  # 2MB
                    raise forms.ValidationError('El tamaño de la imagen no debe exceder los 2MB.')
        return texto

parrafos/views.py
from django.shortcuts import render, redirect
from .models import Parrafo
from .forms import ParrafoForm

def mostrar_texto(request):
    parrafos = Parrafo.objects.all().order_by('fecha_creacion')
    return render(request, 'parrafos/mostrar_texto.html', {'parrafos': parrafos})

def anadir_parrafo(request):
    if request.method == 'POST':
        form = ParrafoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('mostrar_texto')
        else:
            print("Form is not valid")
            print(form.errors)
    else:
        form = ParrafoForm()
    return render(request, 'parrafos/anadir_parrafo.html', {'form': form})

parrafos/templates/parrafos/anadir_parrafo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DesertorEX</title>
    {% load static %}
    <link rel="icon" href="{% static 'parrafos/logo_deser.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'parrafos/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Carlito&display=swap" rel="stylesheet">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet"> <!-- Quill CSS -->
</head>
<body>
    <div id="contenido-anadir" class="form-container">
        <h1>Añadir nueva deserción</h1>
        {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <form method="post" enctype="multipart/form-data" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_titulo">Título:</label>
                {{ form.titulo }}
            </div>
            <div class="form-group">
                <label for="id_autor">Escrito por:</label>
                {{ form.autor }}
            </div>
            <div class="form-group">
                <label for="id_texto">Texto:</label>
                <div id="editor-container"></div> <!-- Contenedor de Quill -->
                <textarea name="texto" id="id_texto" style="display:none;"></textarea> <!-- Campo de texto oculto -->
            </div>
            <input type="file" id="imageInput" accept="image/*" style="display: none;" /> <!-- Solo permitir imágenes -->
            <button type="submit">Añadir</button>
        </form>
        <a href="{% url 'mostrar_texto' %}"><button class="back-button">Volver</button></a>
    </div>
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script> <!-- Quill JS -->
    <script>
        var quill = new Quill('#editor-container', {
            theme: 'snow',
            modules: {
                toolbar: {
                    container: [
                        [{ 'header': [1, 2, 3, false] }],
                        ['bold', 'italic', 'underline'],
                        ['link', 'image'],
                        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                        [{ 'script': 'sub' }, { 'script': 'super' }],
                        [{ 'align': [] }],
                        ['clean']                               // remove formatting button
                    ],
                    handlers: {
                        image: imageHandler
                    }
                }
            }
        });

        function imageHandler() {
            var input = document.getElementById('imageInput');
            input.click();
            input.onchange = () => {
                var file = input.files[0];
                if (!file.type.startsWith('image/')) {
                    alert('Solo se permiten archivos de imagen.'); // Verificar tipo de archivo
                    return;
                }
                if (file.size > 2 * 1024 * 1024) {
                    alert('El tamaño de la imagen no debe exceder los 2MB. Por favor, reduce la calidad de la imagen y vuelve a intentarlo.');
                    return;
                }
                var reader = new FileReader();
                reader.onload = (e) => {
                    var range = quill.getSelection();
                    quill.insertEmbed(range.index, 'image', e.target.result);
                };
                reader.readAsDataURL(file);
            };
        }

        function validateForm() {
            var quillText = document.querySelector('textarea[name=texto]');
            quillText.value = quill.root.innerHTML; // Copiar el contenido HTML de Quill al textarea oculto
            return true;
        }
    </script>
</body>
</html>

parrafos/templates/parrafos/mostrar_texto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>DesertorEX</title>
    {% load static %}
    <link rel="icon" href="{% static 'parrafos/logo_deser.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'parrafos/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Carlito&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="header">
        <div class="header-left">
            <button class="indice-btn" onclick="toggleIndice()">Índice</button>
            <a href="{% url 'anadir_parrafo' %}">
                <button class="indice-btn">Añade tu deserción</button>
            </a>
        </div>
        <div class="header-right">
            <button class="indice-btn" onclick="showPopup('quePopup')">DesertorEX</button>
            <button class="indice-btn" onclick="showPopup('autoedicionesPopup')">Autoediciones La Porvenir</button>
            <button class="indice-btn" onclick="showPopup('codigoPopup')">Código y licencia</button>
            <a href="https://instagram.com/la_porvenir" target="_blank" class="instagram-icon">
                <i class="fab fa-instagram"></i>
            </a>
        </div>
    </div>
    <div id="mySidebar" class="sidebar">
        <h2>Índice</h2>
        <ul id="indice">
            {% for parrafo in parrafos %}
                <li><a href="#{{ parrafo.get_anchor }}" onclick="scrollToElement(event, '{{ parrafo.get_anchor }}')">{{ parrafo.titulo }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <div id="contenido">
        <!-- Nuevo contenido reemplazando el texto de "Las Aventuras de un Botijo en Altamar" -->
        <h1 class="titulo-desertorex">
            DESERTOR<span class="highlight">EX</span>
          </h1>
        <p class="texto-desertorex">
            “Nuestra estrategia es pues la siguiente: establecer
            desde ahora un conjunto de focos de deserción, de<br>
            polos de secesión, de puntos de concentración. Para
            los fugitivos. Para los que se van. Un conjunto de<br>
            lugares en los cuales sustraerse al imperio de una
            civilización que camina hacia el precipicio. De lo que<br>
            se trata es de darse los medios, de encontrar la
            escala donde puedan resolverse el conjunto de<br>
            cuestiones que, planteadas a cada uno
            separadamente, conducen a la depresión. ¿Cómo<br>
            deshacerse de las dependencias que nos debilitan?
            ¿Cómo organizarse para dejar de trabajar? ¿Cómo<br>
            establecerse fuera de la toxicidad de las metrópolis
            sin, por otro lado, «irse al campo»? ¿Cómo detener<br>
            las centrales nucleares? ¿Cómo hacer para no verse
            forzado a recurrir a la trituración psiquiátrica cuando<br>
            un amigo se vuelve loco, a los medicamentos burdos
            de la medicina mecanicista cuando cae enfermo?<br>
            ¿Cómo vivir juntos sin aplastarse mutuamente?
            ¿Cómo acoger la muerte de un camarada? ¿Cómo<br>
            arruinar al imperio?"
        </p>
        <p class="llamamiento">Llamamiento (2003)</p>
        
        <div id="texto">
            {% for parrafo in parrafos %}
                <div class="parrafo" id="{{ parrafo.get_anchor }}">
                    <p class="titulo">{{ parrafo.titulo }}</p>
                    <p class="autor"><em>Escrito por: {{ parrafo.autor }}</em></p>
                    <p>{{ parrafo.texto|safe }}</p> <!-- Usa el filtro safe para renderizar HTML -->
                </div>
            {% endfor %}
        </div>
    </div>

    <div id="quePopup" class="popup" onclick="event.stopPropagation()">
        <p>DesertorEX es una recopilación de experiencias sobre el proceso de desertar de la psiquiatrización de las situaciones difíciles. Como profesional, como paciente y como entorno cómplice. Con desertar nos referimos a dejar de ser profesional, dejar de ser paciente, dejar de ser entorno y cómplice, y a que todo el mundo hagamos otra cosa con lo que pasa.</p>

        <p>En DesertorEX encontrarás experiencias concretas, no las mejores, no terminadas, no exentas de ambivalencia, con las que no estamos necesariamente de acuerdo, pero todas intentos reales, y por tanto útiles, para poder acercarse a los movimientos que cada cúal tendría que hacer para salir de este embrollo y mirar de frente qué es lo que los atasca y qué es lo que los desatasca. Incluye unas explicaciones iniciales sobre la práctica que nos ha llevado a la convicción de que es por aquí, y sus consecuencias, también sobre cómo se ha hecho la recopilación y qué ha pasado por el camino.</p>

        <p>Ahora es tu turno, te animamos a escribir la tuya, tu experiencia de deserción.</p>

        <p>Si quieres ponerte en contacto con nosotres para proponernos proyectos al respecto escríbenos a <a href="mailto:desertorex@laporvenir.org">desertorex@laporvenir.org</a></p>
        <p>Si quieres ejemplares físicos del primer recopilatorio de textos escríbenos a <a href="mailto:autoediciones@laporvenir.org">autoediciones@laporvenir.org</a></p>
    </div>
    <div id="autoedicionesPopup" class="popup" onclick="event.stopPropagation()">
        <p><a href="https://laporvenir.org/que-hacemos/autoediciones/" target="_blank">Todo esto no sale de la nada.</a> Mucho de atreverse, muchos palos, muchos desencuentros, muchas conversaciones y reuniones, mucho pensar en común, mucha gente, mucho conocimiento acumulado puesto en práctica, mucha autogestión.</p>

    <p>Apostamos por la cultura libre. Pedimos que se ponga conciencia en que libre no significa gratis, así que si quieres redistribuir lo que sí que tienes con nosotres puedes consultar cómo hacerlo <a href="https://laporvenir.org/tu/" target="_blank">aquí</a>.</p>
    </div>
    <div id="codigoPopup" class="popup" onclick="event.stopPropagation()">
        <p>Licencia de Producción de Pares</p>
    
        <p><img src="{% static 'parrafos/licencianegro.png' %}" alt="licencia" ></p>
        
        <p>Atribución<br>Compartir bajo la Misma Licencia<br> No capitalista</p>
        
        <p>Licencia completa <a href="https://endefensadelsl.org/ppl_deed_es.html" target="_blank">aquí</a></p>

        <p>Código fuente de la página disponible aquí  <a href="https://github.com/sagarrabanana/editable" target="_blank">
            <img src="{% static 'parrafos/github-mark.png' %}" alt="repo" width="30" height="30">
        </a></p>

        <p>Septiembre 2024</p>

    </div>

    <script>
        function toggleIndice() {
            var sidebar = document.getElementById("mySidebar");
            var contenido = document.getElementById("contenido");
            if (sidebar.classList.contains('open')) {
                sidebar.classList.remove('open');
                contenido.classList.remove('shifted');
            } else {
                sidebar.classList.add('open');
                contenido.classList.add('shifted');
            }
        }

        function scrollToElement(event, id) {
            event.preventDefault();
            var element = document.getElementById(id);
            var headerOffset = document.querySelector('.header').offsetHeight;
            var elementPosition = element.getBoundingClientRect().top;
            var offsetPosition = elementPosition + window.pageYOffset - headerOffset;

            window.scrollTo({
                top: offsetPosition,
                behavior: 'smooth'
            });
        }

        function showPopup(popupId) {
            var popup = document.getElementById(popupId);
            popup.style.display = 'block';
            setTimeout(() => document.addEventListener('click', closePopupOnClickOutside), 0);
        }

        function closePopupOnClickOutside(event) {
            const popups = document.querySelectorAll('.popup');
            popups.forEach(popup => {
                if (popup.style.display === 'block' && !popup.contains(event.target)) {
                    popup.style.display = 'none';
                }
            });
            document.removeEventListener('click', closePopupOnClickOutside);
        }
    </script>
</body>
</html>